[theme]
primaryColor = "#F63366"
backgroundColor = "#000000"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"

[client]
showGitHubIcon = false
